[package]
name = "grepdef"
version = "3.0.0"
edition = "2021"
repository = "https://github.com/sirbrillig/grepdef"
homepage = "https://github.com/sirbrillig/grepdef"
description = "Quick search for symbol definitions in various programming languages"
license-file = "LICENSE"
documentation = "https://docs.rs/grepdef/latest/grepdef"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
colored = "2.1.0"
exitcode = "1.1.2"
ignore = "0.4.22"
memchr = "2.7.4"
regex = "1.10.5"
rstest = "0.21.0"
strum = "0.26.3"
strum_macros = "0.26.4"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.19.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "npm"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# The archive format to use for windows builds (defaults .zip)
windows-archive = ".tar.gz"
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
# A namespace to use when publishing this package to the npm registry
npm-scope = "@sirbrillig"
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Publish jobs to run in CI
pr-run-mode = "plan"
# Whether to install an updater program
install-updater = false
